# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "tailscale-ingress"
primary_region = "arn"

[env]
  TS_USERSPACE = "false"
  REDIRECT_TARGET = "10.20.0.200"

[[services]]
  internal_port = 80
  protocol = "tcp"
  [[services.ports]]
    port = 80

[[services]]
  internal_port = 443
  protocol = "tcp"
  [[services.ports]]
    port = 443
