# fly.toml file generated for tailscale-ingress on 2022-12-01T04:37:48+01:00

app = "tailscale-ingress"

[env]
  TS_USERSPACE = "false"

[[services]]
  internal_port = 80
  protocol = "tcp"
  [[services.ports]]
    port = 80

[[services]]
  internal_port = 443
  protocol = "tcp"
  [[services.ports]]
    port = 443
