# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "tailscale-ingress"
primary_region = "arn"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  TS_USERSPACE = "false"
  REDIRECT_TARGET = "10.20.0.200"

[[services]]
  internal_port = 80
  protocol = "tcp"
  [[services.ports]]
    port = 80
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[services]]
  internal_port = 443
  protocol = "tcp"
  [[services.ports]]
    port = 443
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
